[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-nextjs" 